"""F0 pour-extraction tests.

Guards and fixture
------------------
All tests that touch pcbnew are skipped when pcbnew is unavailable (same
pattern as existing pcbnew-dependent tests in the repo).  The fixture boards
are pre-generated by ``tests/fixtures/build_pour_fixture.py``; they must exist
before running the tests.

Fixture topology (F.Cu only, 30×30 mm, one GND zone):
  GND zone polygon: (1,1)→(20,1)→(20,20)→(1,20)
  R1 pad at  (5,  5) — inside zone → connected via fill
  R2 pad at (10, 10) — inside zone → connected via fill
  R3 pad at (25, 25) — outside zone → ISOLATED (the stitch worklist entry)

Two boards are tested:
  pour_source.kicad_pcb  — original build
  pour_resaved.kicad_pcb — pcbnew round-trip of source

The core invariant: identical results on both boards defeats the s-expr
net_name fragility described in F0-pour-extraction.md.
"""

from __future__ import annotations

import math
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# pcbnew availability guard (mirrors test_engine.py pattern)
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SOURCE_BOARD = FIXTURE_DIR / "pour_source.kicad_pcb"
RESAVED_BOARD = FIXTURE_DIR / "pour_resaved.kicad_pcb"


def _pcbnew_available() -> bool:
    try:
        import subprocess
        r = subprocess.run(
            ["python3", "-c", "import pcbnew"],
            capture_output=True, text=True, timeout=10,
        )
        return r.returncode == 0
    except Exception:
        return False


def _fixtures_exist() -> bool:
    return SOURCE_BOARD.exists() and RESAVED_BOARD.exists()


skip_no_kicad = pytest.mark.skipif(
    not _pcbnew_available(),
    reason="pcbnew not available (install KiCad)",
)
skip_no_fixtures = pytest.mark.skipif(
    not _fixtures_exist(),
    reason=(
        "Fixture boards missing — run "
        "python3 tests/fixtures/build_pour_fixture.py"
    ),
)

needs_kicad = pytest.mark.usefixtures()  # combined below per-test


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _poly_area(pts: list[tuple[float, float]]) -> float:
    """Shoelace formula, absolute value."""
    n = len(pts)
    if n < 3:
        return 0.0
    area = 0.0
    for i in range(n):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % n]
        area += x1 * y2 - x2 * y1
    return abs(area) / 2.0


# ---------------------------------------------------------------------------
# extract_pours tests
# ---------------------------------------------------------------------------


@skip_no_kicad
@skip_no_fixtures
def test_extract_pours_returns_gnd_key():
    """extract_pours must return a 'GND' key for the fixture board."""
    from tracewise.route.engine.pours import extract_pours

    result = extract_pours(SOURCE_BOARD)
    assert "GND" in result, f"Expected 'GND' in {list(result.keys())}"


@skip_no_kicad
@skip_no_fixtures
def test_extract_pours_polygon_geometry():
    """The GND pour must have at least one polygon with area ≈ zone area.

    The GND zone covers (1,1)→(20,20) = 19×19 = 361 mm².  The actual fill
    will be slightly smaller (clearance and thermal relief remove area), so we
    check that at least one polygon covers ≥ 300 mm².
    """
    from tracewise.route.engine.pours import extract_pours

    polys = extract_pours(SOURCE_BOARD)["GND"]
    # All polys should be on layer 0 (F.Cu) for this fixture
    assert all(p.layer == 0 for p in polys), "All fixture pours should be on F.Cu (layer 0)"
    total_area = sum(_poly_area(p.pts) for p in polys)
    assert total_area >= 200.0, f"Total GND pour area {total_area:.1f} mm² < expected minimum"


@skip_no_kicad
@skip_no_fixtures
def test_extract_pours_identical_across_formats():
    """Core F0 gate: extract_pours gives identical results on source vs resaved.

    This is the direct test of the anti-fragility claim in F0-pour-extraction.md:
    pcbnew's GetNetname() is stable across save-format variants, unlike s-expr
    net_name which can be absent on resaved boards.
    """
    from tracewise.route.engine.pours import extract_pours

    src = extract_pours(SOURCE_BOARD)
    rsv = extract_pours(RESAVED_BOARD)

    # Same net keys
    assert set(src.keys()) == set(rsv.keys()), (
        f"Net key mismatch: source={set(src.keys())} resaved={set(rsv.keys())}"
    )

    for net in src:
        src_polys = src[net]
        rsv_polys = rsv[net]
        # Same number of polygons
        assert len(src_polys) == len(rsv_polys), (
            f"net={net}: polygon count source={len(src_polys)} resaved={len(rsv_polys)}"
        )
        for i, (sp, rp) in enumerate(zip(src_polys, rsv_polys, strict=True)):
            # Same layer
            assert sp.layer == rp.layer, f"net={net} poly {i}: layer mismatch"
            # Same point count
            assert len(sp.pts) == len(rp.pts), (
                f"net={net} poly {i}: point count {len(sp.pts)} vs {len(rp.pts)}"
            )
            # Same area within 0.1 mm² tolerance
            area_src = _poly_area(sp.pts)
            area_rsv = _poly_area(rp.pts)
            assert math.isclose(area_src, area_rsv, abs_tol=0.1), (
                f"net={net} poly {i}: area source={area_src:.3f} resaved={area_rsv:.3f}"
            )


# ---------------------------------------------------------------------------
# unconnected_pads tests
# ---------------------------------------------------------------------------


@skip_no_kicad
@skip_no_fixtures
def test_unconnected_pads_finds_only_isolated():
    """unconnected_pads must return exactly R3 (the isolated pad).

    R1 and R2 are inside the GND zone and connected via fill; R3 at (25,25) is
    outside the zone polygon and has no copper path to the pour.
    """
    from tracewise.route.engine.pours import unconnected_pads

    isolated = unconnected_pads(SOURCE_BOARD)

    assert len(isolated) == 1, (
        f"Expected exactly 1 isolated GND pad, got {len(isolated)}: "
        + str([(p.ref, p.pad) for p in isolated])
    )
    pad = isolated[0]
    assert pad.net == "GND"
    assert pad.ref == "R3"
    assert pad.pad == "1"
    assert math.isclose(pad.x, 25.0, abs_tol=0.01)
    assert math.isclose(pad.y, 25.0, abs_tol=0.01)
    # Through-hole pad → on both layers
    assert 0 in pad.layers  # F.Cu
    assert 1 in pad.layers  # B.Cu


@skip_no_kicad
@skip_no_fixtures
def test_unconnected_pads_identical_across_formats():
    """Core F0 gate: unconnected_pads gives identical results on source vs resaved."""
    from tracewise.route.engine.pours import unconnected_pads

    src = unconnected_pads(SOURCE_BOARD)
    rsv = unconnected_pads(RESAVED_BOARD)

    assert len(src) == len(rsv), (
        f"Isolated pad count: source={len(src)} resaved={len(rsv)}"
    )
    for sp, rp in zip(src, rsv, strict=True):
        assert sp.net == rp.net, f"net mismatch: {sp.net!r} vs {rp.net!r}"
        assert sp.ref == rp.ref, f"ref mismatch: {sp.ref!r} vs {rp.ref!r}"
        assert sp.pad == rp.pad, f"pad mismatch: {sp.pad!r} vs {rp.pad!r}"
        assert math.isclose(sp.x, rp.x, abs_tol=0.001)
        assert math.isclose(sp.y, rp.y, abs_tol=0.001)
        assert sp.layers == rp.layers


# ---------------------------------------------------------------------------
# rasterize_pour tests (pure numpy — no kicad needed)
# ---------------------------------------------------------------------------


def _make_grid(w: float = 20.0, h: float = 20.0, pitch: float = 0.1):
    from tracewise.route.engine.grid import Grid

    return Grid(x0=0.0, y0=0.0, width_mm=w, height_mm=h, pitch=pitch)


def test_rasterize_pour_marks_interior():
    """Interior cells of a simple rectangle pour must be True, exterior False.

    Pour: (2,2)→(8,8) on layer 0.  Grid: 20×20 mm, pitch 0.1 mm.
    Known interior point: (5, 5) → cell (50, 50).
    Known exterior point: (1, 1) → cell (10, 10).
    """
    from tracewise.route.engine.pours import PourPoly, rasterize_pour

    grid = _make_grid()
    rect_pts = [(2.0, 2.0), (8.0, 2.0), (8.0, 8.0), (2.0, 8.0)]
    polys = [PourPoly(net="GND", layer=0, pts=rect_pts)]
    mask = rasterize_pour(grid, polys)

    assert mask.shape == (2, grid.ny, grid.nx)
    assert mask.dtype == bool

    # Interior
    iy_in, ix_in = grid.to_cell(5.0, 5.0)
    assert mask[0, iy_in, ix_in], "Centre of pour rectangle should be True"

    # Exterior
    iy_out, ix_out = grid.to_cell(1.0, 1.0)
    assert not mask[0, iy_out, ix_out], "Outside pour rectangle should be False"

    # Correct layer only
    assert not mask[1, iy_in, ix_in], "Layer 1 should be untouched"


def test_rasterize_pour_layer_separation():
    """A pour on layer 1 must not affect layer 0."""
    from tracewise.route.engine.pours import PourPoly, rasterize_pour

    grid = _make_grid()
    polys = [PourPoly(net="GND", layer=1, pts=[(3.0, 3.0), (7.0, 3.0), (7.0, 7.0), (3.0, 7.0)])]
    mask = rasterize_pour(grid, polys)

    iy, ix = grid.to_cell(5.0, 5.0)
    assert mask[1, iy, ix], "Layer 1 interior should be True"
    assert not mask[0, iy, ix], "Layer 0 should be untouched"


def test_rasterize_pour_union_across_polys():
    """Two disjoint polygons on the same layer produce a union mask."""
    from tracewise.route.engine.pours import PourPoly, rasterize_pour

    grid = _make_grid()
    poly_a = PourPoly(net="GND", layer=0, pts=[(1.0, 1.0), (4.0, 1.0), (4.0, 4.0), (1.0, 4.0)])
    poly_b = PourPoly(net="GND", layer=0, pts=[(6.0, 6.0), (9.0, 6.0), (9.0, 9.0), (6.0, 9.0)])
    mask = rasterize_pour(grid, [poly_a, poly_b])

    iy_a, ix_a = grid.to_cell(2.5, 2.5)
    iy_b, ix_b = grid.to_cell(7.5, 7.5)
    iy_gap, ix_gap = grid.to_cell(5.0, 5.0)

    assert mask[0, iy_a, ix_a], "Centre of poly_a should be True"
    assert mask[0, iy_b, ix_b], "Centre of poly_b should be True"
    assert not mask[0, iy_gap, ix_gap], "Gap between polygons should be False"


def test_rasterize_pour_off_by_one_at_bbox_edges():
    """Cells at the interior corners of the bbox must be True; just outside False.

    The bbox of a 4×4 mm square at (2,2)→(6,6) has corners at exactly those
    coords.  The cell AT (2,2) has its centre at (2,2) which lies ON the edge
    and the Jordan test treats it as interior (crossing parity).  The cell at
    (1.9, 1.9) is strictly outside and must be False.
    """
    from tracewise.route.engine.pours import PourPoly, rasterize_pour

    grid = _make_grid()
    # 4×4 mm square, strictly defined corners
    polys = [PourPoly(net="GND", layer=0, pts=[(2.0, 2.0), (6.0, 2.0), (6.0, 6.0), (2.0, 6.0)])]
    mask = rasterize_pour(grid, polys)

    # Well inside
    iy_in, ix_in = grid.to_cell(4.0, 4.0)
    assert mask[0, iy_in, ix_in], "Well-interior cell must be True"

    # Well outside
    iy_out, ix_out = grid.to_cell(1.0, 1.0)
    assert not mask[0, iy_out, ix_out], "Well-exterior cell must be False"


def test_rasterize_pour_empty_list():
    """Empty polygon list returns all-False mask of correct shape."""
    from tracewise.route.engine.pours import rasterize_pour

    grid = _make_grid()
    mask = rasterize_pour(grid, [])
    assert mask.shape == (2, grid.ny, grid.nx)
    assert not mask.any()


def test_rasterize_pour_out_of_bounds_layer_skipped():
    """Polygons on a layer index outside [0, grid.layers) are silently skipped."""
    from tracewise.route.engine.pours import PourPoly, rasterize_pour

    grid = _make_grid()
    bad_poly = PourPoly(net="GND", layer=99, pts=[(2.0, 2.0), (8.0, 2.0), (8.0, 8.0), (2.0, 8.0)])
    mask = rasterize_pour(grid, [bad_poly])
    assert not mask.any(), "Out-of-range layer poly should produce all-False mask"


@skip_no_kicad
@skip_no_fixtures
def test_rasterize_pour_with_real_extract():
    """End-to-end: rasterize the GND pour from the fixture board.

    Verifies that the polygon returned by extract_pours rasterizes to at
    least one True cell and that the True region covers a reasonable fraction
    of the zone area (between 1% and 90% of the grid).
    """
    from tracewise.route.engine.grid import Grid
    from tracewise.route.engine.pours import extract_pours, rasterize_pour

    polys_by_net = extract_pours(SOURCE_BOARD)
    gnd_polys = polys_by_net.get("GND", [])
    assert gnd_polys, "No GND pour found in fixture board"

    # Build a grid that covers the fixture board (30×30 mm)
    grid = Grid(x0=0.0, y0=0.0, width_mm=30.0, height_mm=30.0, pitch=0.1)
    mask = rasterize_pour(grid, gnd_polys)

    true_count = mask.sum()
    total_cells = grid.layers * grid.ny * grid.nx
    fraction = true_count / total_cells

    assert true_count > 0, "rasterize_pour produced all-False mask for real fixture"
    assert fraction < 0.9, f"Suspiciously large pour fraction: {fraction:.3f}"
    assert fraction > 0.001, f"Suspiciously small pour fraction: {fraction:.4f}"

    # The pour should be on layer 0 (F.Cu) only for this fixture
    assert mask[0].any(), "F.Cu layer (0) should have True cells"
    assert not mask[1].any(), "B.Cu layer (1) should be empty for this fixture"
